# -*- coding: utf-8 -*-
"""GameMaster_IA_Topicos_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6BkVobFpTy0IfDPhwwPSU0meSmCp8kb
"""

# GameMaster IA

## 1. Introdução
## 2. Objetivo
## 3. Base de Dados
## 4. Pré-processamento
## 5. Treinamento dos Modelos
## 6. Avaliação
## 7. Testes com Jogadores Simulados
## 8. Conclusão

!pip install -q google-generativeai

import google.generativeai as genai
from google.colab import userdata

import pandas as pd
import typing

MINHA_CHAVE = userdata.get("GEMINI_API_KEY")

genai.configure(api_key=MINHA_CHAVE)

print("Chave carregada com sucesso.")

modelo = genai.GenerativeModel("gemini-2.5-flash")

print("Modelo Gemini criado.")

eras_games = {
    "era": [
        "Atari / Arcade",
        "NES / Master System",
        "SNES / Mega Drive",
        "PS1 / Nintendo 64 / Saturn",
        "PS2 / GameCube / Xbox"
    ],
    "periodo": [
        "1977-1983",
        "1983-1990",
        "1990-1996",
        "1994-2001",
        "2000-2006"
    ],
    "caracteristicas": [
        "Jogos simples, foco em pontuação, reflexo e repetição",
        "Fases lineares, chefes, vidas limitadas e progressão por mundos",
        "Sprites detalhados, trilhas marcantes, narrativa mais presente",
        "Ambientes 3D, cinemáticas, diálogos e histórias mais complexas",
        "Mundos maiores, dublagem, missões, progressão e clima cinematográfico"
    ]
}

df_eras = pd.DataFrame(eras_games)

df_eras

jogos_referencia = {
    "jogo": [
        "Pong",
        "Space Invaders",
        "Pitfall!",
        "Super Mario Bros.",
        "The Legend of Zelda",
        "Mega Man",
        "Sonic the Hedgehog",
        "Chrono Trigger",
        "Streets of Rage",
        "Final Fantasy VII",
        "Resident Evil",
        "Metal Gear Solid",
        "Crash Bandicoot",
        "GTA San Andreas",
        "God of War",
        "Shadow of the Colossus"
    ],
    "era": [
        "Atari / Arcade",
        "Atari / Arcade",
        "Atari / Arcade",
        "NES / Master System",
        "NES / Master System",
        "NES / Master System",
        "SNES / Mega Drive",
        "SNES / Mega Drive",
        "SNES / Mega Drive",
        "PS1 / Nintendo 64 / Saturn",
        "PS1 / Nintendo 64 / Saturn",
        "PS1 / Nintendo 64 / Saturn",
        "PS1 / Nintendo 64 / Saturn",
        "PS2 / GameCube / Xbox",
        "PS2 / GameCube / Xbox",
        "PS2 / GameCube / Xbox"
    ],
    "genero": [
        "Arcade",
        "Tiro / Arcade",
        "Aventura",
        "Plataforma",
        "Aventura",
        "Ação / Plataforma",
        "Plataforma",
        "RPG",
        "Beat'em up",
        "RPG",
        "Survival horror",
        "Stealth / Ação",
        "Plataforma",
        "Mundo aberto",
        "Ação / Aventura",
        "Ação / Aventura"
    ]
}

df_jogos = pd.DataFrame(jogos_referencia)

df_jogos

def montar_contexto_games():
    contexto = "Base histórica de jogos digitais usada pelo GameMaster IA:\n\n"

    contexto += "ERAS DOS GAMES:\n"
    for _, linha in df_eras.iterrows():
        contexto += f"- {linha['era']} ({linha['periodo']}): {linha['caracteristicas']}\n"

    contexto += "\nJOGOS DE REFERÊNCIA:\n"
    for _, linha in df_jogos.iterrows():
        contexto += f"- {linha['jogo']} | Era: {linha['era']} | Gênero: {linha['genero']}\n"

    return contexto


contexto_games = montar_contexto_games()

print(contexto_games)

prompt = f"""
Crie uma sinopse criativa para o projeto GameMaster IA.

O GameMaster IA é uma aplicação que usa IA generativa para criar histórias,
missões e diálogos inspirados em jogos antigos, da era Atari até PS2.

Use como apoio esta base histórica:

{contexto_games}
"""

resposta = modelo.generate_content(prompt)

print(resposta.text)

instrucao_gamemaster = """
Você é o GameMaster IA, um mestre de jogo narrativo, criativo e nostálgico.

Seu papel é criar histórias, missões, diálogos e eventos inspirados em jogos antigos,
desde a era Atari até o PlayStation 2.

Seu estilo deve misturar:
- clima de fliperama antigo;
- aventura 8-bit e 16-bit;
- mistério de jogos de PS1;
- narrativa cinematográfica de PS2.

Regras:
- Não copie personagens famosos.
- Não use nomes protegidos de franquias reais.
- Crie tudo de forma original.
- Escreva em português brasileiro.
- Seja criativo, mas mantenha organização.
"""

modelo_gamemaster = genai.GenerativeModel(
    "gemini-2.5-flash",
    system_instruction=instrucao_gamemaster
)

print("Persona GameMaster IA criada.")

prompt_historia = f"""
Com base neste contexto histórico:

{contexto_games}

Crie uma história original de um jogo retrô chamado "Cartucho Perdido".

A história deve conter:
1. Título
2. Era de inspiração
3. Protagonista
4. Mundo do jogo
5. Vilão
6. Objetivo principal
7. Mecânicas principais
8. Final da aventura
"""

resposta_historia = modelo_gamemaster.generate_content(prompt_historia)

print(resposta_historia.text)

instrucao_npc = """
Você é um NPC misterioso de um RPG retrô.

Você fala como um personagem antigo de jogo, com frases enigmáticas,
mas ainda compreensíveis.

Você deve parecer um personagem que vive dentro de um cartucho antigo amaldiçoado.
Suas respostas devem ser dramáticas, criativas e com clima de jogo de PS1.
"""

modelo_npc = genai.GenerativeModel(
    "gemini-2.5-flash",
    system_instruction=instrucao_npc
)

resposta_npc = modelo_npc.generate_content(
    "Um jogador acabou de entrar no mundo do cartucho perdido. Dê as boas-vindas a ele."
)

print(resposta_npc.text)

instrucao_dev = """
Você é um desenvolvedor de jogos experiente e direto.

Sua função é analisar ideias de jogos e explicar se elas seriam viáveis como protótipo.
Fale de forma técnica, mas simples para um estudante apresentar em sala.
"""

modelo_dev = genai.GenerativeModel(
    "gemini-2.5-flash",
    system_instruction=instrucao_dev
)

resposta_dev = modelo_dev.generate_content(
    "Analise se o jogo Cartucho Perdido seria viável como protótipo acadêmico."
)

print(resposta_dev.text)

chat = modelo_gamemaster.start_chat(history=[])

print("Chat iniciado.")

resp1 = chat.send_message("""
Olá, GameMaster IA.
Eu sou um jogador perdido dentro de um cartucho antigo.
Onde eu estou?
""")

print("GameMaster IA:")
print(resp1.text)

resp2 = chat.send_message("""
Eu vejo uma cidade cheia de máquinas arcade quebradas.
Existe algum NPC por perto?
""")

print("GameMaster IA:")
print(resp2.text)

resp3 = chat.send_message("""
Quero conversar com esse NPC.
Crie um diálogo entre eu e ele.
O NPC deve parecer misterioso e saber algo sobre o vilão.
""")

print("GameMaster IA:")
print(resp3.text)

resp4 = chat.send_message("""
Agora crie uma missão para mim.

A missão precisa ter:
- objetivo principal;
- item especial;
- inimigos;
- recompensa;
- uma escolha moral no final.
""")

print("GameMaster IA:")
print(resp4.text)

resp5 = chat.send_message("""
Crie uma batalha contra chefe no estilo PS1/PS2.

O chefe deve ser original e relacionado a bugs, glitches e arquivos corrompidos.
Explique os ataques dele e como o jogador pode vencer.
""")

print("GameMaster IA:")
print(resp5.text)

print(chat.history)

prompt_conversa_completa = """
Crie uma conversa completa e criativa para o jogo GameMaster IA.

Contexto:
O jogador acorda dentro de um cartucho antigo chamado "Cartucho Perdido".
O mundo mistura Atari, SNES, PS1 e PS2.
Existe um NPC chamado Oráculo dos Pixels.
O vilão é uma entidade chamada Bug Supremo, que corrompe fases antigas.

A conversa deve ter:
- Narrador
- Jogador
- Oráculo dos Pixels
- Bug Supremo
- Pelo menos 12 falas
- Clima de aventura retrô
- Um mistério
- Uma missão
- Um momento engraçado
- Uma decisão importante no final

Não copie personagens famosos.
Crie uma cena original.
"""

resposta_conversa = modelo_gamemaster.generate_content(prompt_conversa_completa)

print(resposta_conversa.text)

prompt_roteiro = """
Transforme a ideia do GameMaster IA em um roteiro de cena para apresentação.

Formato obrigatório:

CENA 1 - Título da cena
NARRADOR:
JOGADOR:
NPC:
GAMEMASTER IA:
VILÃO:

A cena deve parecer uma mistura de jogo de fliperama, RPG 16-bit e aventura de PS2.
A conversa precisa ser criativa, com começo, meio e fim.
"""

resposta_roteiro = modelo_gamemaster.generate_content(prompt_roteiro)

print(resposta_roteiro.text)

class FichaJogo(typing.TypedDict):
    titulo: str
    era_inspiracao: str
    genero: str
    protagonista: str
    vilao: str
    objetivo: str
    mecanicas: list[str]
    publico_alvo: str

prompt_json = """
Crie a ficha técnica de um jogo original chamado Cartucho Perdido.

O jogo deve ser inspirado em games antigos da era Atari até PS2.
Não use personagens famosos.
Crie tudo de forma original.
"""

resposta_json = modelo_gamemaster.generate_content(
    prompt_json,
    generation_config=genai.GenerationConfig(
        response_mime_type="application/json",
        response_schema=FichaJogo
    )
)

print(resposta_json.text)

class PersonagemGameMaster(typing.TypedDict):
    nome: str
    funcao: str
    personalidade: str
    habilidades: list[str]
    frase_marcante: str

prompt_personagem = """
Crie um personagem original para o GameMaster IA.

Ele deve ser um NPC que vive em uma fase corrompida de um jogo antigo.
Ele precisa ajudar o jogador, mas também esconder um segredo.
"""

resposta_personagem = modelo_gamemaster.generate_content(
    prompt_personagem,
    generation_config=genai.GenerationConfig(
        response_mime_type="application/json",
        response_schema=PersonagemGameMaster
    )
)

print(resposta_personagem.text)

instrucao_avaliador = """
Você é um avaliador acadêmico de projetos de IA Generativa.

Avalie se a história criada pelo GameMaster IA é:
- criativa;
- coerente;
- adequada ao tema de jogos antigos;
- útil para uma aplicação web;
- fácil de apresentar em sala.

Dê uma nota de 0 a 10 e justifique.
"""

modelo_avaliador = genai.GenerativeModel(
    "gemini-2.5-flash",
    system_instruction=instrucao_avaliador
)

print("Modelo avaliador criado.")

avaliacao = modelo_avaliador.generate_content(
    f"""
Avalie a conversa abaixo:

{resposta_conversa.text}
"""
)

print(avaliacao.text)

prompt_resumo = """
Crie um resumo acadêmico do projeto GameMaster IA.

Explique:
1. Qual problema o projeto resolve.
2. Como a IA Generativa foi usada.
3. Como a aplicação poderia funcionar.
4. Por que o projeto atende aos requisitos da disciplina.
5. O que será demonstrado na apresentação.
"""

resposta_resumo = modelo_gamemaster.generate_content(prompt_resumo)

print(resposta_resumo.text)

prompt_readme = """
Crie um README para o projeto GameMaster IA.

O README deve conter:
- Título
- Descrição
- Problema escolhido
- Solução proposta
- Tecnologias utilizadas
- Como a IA Generativa foi integrada
- Como executar no Google Colab
- Funcionalidades
- Conclusão
"""

resposta_readme = modelo_gamemaster.generate_content(prompt_readme)

print(resposta_readme.text)